#######################################################################################
# ___       __    ______ ______              __________                 ______        #
# __ |     / /_______  /____  /________________  /___(_)_____________ _ ___  /______  #
# __ | /| / /_  _ \_  __ \_  __ \  __ \_  ___/  __/_  /__  __ \_  __ `/ __  __ \  _ \ #
# __ |/ |/ / /  __/  /_/ /  / / / /_/ /(__  )/ /_ _  / _  / / /  /_/ /___  /_/ /  __/ #
# ____/|__/  \___//_.___//_/ /_/\____//____/ \__/ /_/  /_/ /_/_\__, /_(_)_.___/\___/  # 
#                                                            /____/                   #
#######################################################################################
# Autogit - config and deploy hooks                                                   #
#######################################################################################
# This YAML file, named as "autogit.yml" should be present                            #
# in the root folder of your codebase                                                 # 
#######################################################################################

# Example shared files and folders:
# shared_files: [ etc/config.yml ]
# shared_folders: [ var/log ]

# Hooks should be Bash shell scripts and get executed at different stages during deploy
# Arguments: $1 = branch, $2 = commit id, $3 = checkout folder
diff --git a/.autogit.yml b/.autogit.yml
index 37fdc61..eca3762 100644
--- a/.autogit.yml
+++ b/.autogit.yml
@@ -29,6 +29,7 @@ hooks:
   install_before: |
     exit 0
   install_after: |
+    rm -Rf var/ # Get rid of the git var folder
     exit 0
 
 # SHAREDSYMLINK: Create symlink to shared files and folders
@@ -36,6 +37,9 @@ hooks:
   sharedsymlink_before: |
     exit 0
   sharedsymlink_after: |
+    mkdir -p var/cache
+    mkdir -p var/logs
+    mkdir -p var/sessions
     SYMFONY_ENV=prod composer install --no-dev --classmap-authoritative --prefer-dist
     exit 0